version: '3.8'

services:
  event-processor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PITCHLAKE_DB_URL=postgres://pitchlake_user:pitchlake_password@pitchlake-db:5432/pitchlake?sslmode=disable
    networks:
      - pitchlake-network

networks:
  pitchlake-network:
    external: true
    name: pitchlake-network