# Dockerfile used by the pitchlake-launcher 

# Use Node.js v20 as the base image
FROM node:22-alpine AS builder

# Set the working directory
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files first
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the application
COPY . .

# Build the Next.js application
RUN pnpm run build

# Define the command to run the app
CMD ["sh", "-c", "pnpm start -p ${PORT}"]