version: '3.8'

services:

  #Mock blockheaders database
  fossil-db:
    image: postgres:16
    platform: linux/amd64
    container_name: fossil-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=fossil
      - POSTGRES_USER=fossil_user
      - POSTGRES_PASSWORD=fossil_password
    volumes:
      - fossil_data:/var/lib/postgresql/data
      - ./migrations/fossil:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"
    networks:
      - fossil-monorepo_local-network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U fossil_user -d fossil"]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 10s


  pitchlake-db:
    image: postgres:16
    platform: linux/amd64
    container_name: pitchlake-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=pitchlake
      - POSTGRES_USER=pitchlake_user
      - POSTGRES_PASSWORD=pitchlake_password
    volumes:
      - pitchlake_data:/var/lib/postgresql/data
      - ./migrations/pitchlake:/docker-entrypoint-initdb.d
    ports:
      - "5437:5432"
    networks:
      - fossil-monorepo_local-network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U pitchlake_user -d pitchlake"]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 10s


  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_VAULT_ADDRESSES=${VAULT_ADDRESSES}
        - NEXT_PUBLIC_ENVIRONMENT=rpc
        - NEXT_PUBLIC_RPC_URL_MAINNET=https://starknet-mainnet.public.blastapi.io/rpc/v0_9
        - NEXT_PUBLIC_RPC_URL_SEPOLIA=http://localhost:5050
        - NEXT_PUBLIC_RPC_URL_DEVNET=http://localhost:5050
        - FOSSIL_API_KEY=${FOSSIL_API_KEY}
        - FOSSIL_DB_URL=postgresql://fossil_user:fossil_password@fossil-db:5432/fossil
        - NEXT_PUBLIC_FOSSIL_API_URL=${FOSSIL_API_URL}
    image: pitchlake-frontend:latest  # Use the built image instead of build:
    platform: linux/amd64
    container_name: frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_ENVIRONMENT=rpc
      - NEXT_PUBLIC_RPC_URL_MAINNET=https://starknet-mainnet.public.blastapi.io/rpc/v0_7
      - NEXT_PUBLIC_RPC_URL_SEPOLIA=http://localhost:5050
      - NEXT_PUBLIC_RPC_URL_DEVNET=http://localhost:5050
      - NEXT_PUBLIC_VAULT_ADDRESSES=${NEXT_PUBLIC_VAULT_ADDRESSES}
      - NEXT_PUBLIC_WS_URL=http://localhost:3005
      - FOSSIL_API_KEY=${FOSSIL_API_KEY}
      - NEXT_PUBLIC_FOSSIL_API_URL=${FOSSIL_API_URL}
      - FOSSIL_DB_URL=postgresql://fossil_user:fossil_password@fossil-db:5432/fossil
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - fossil-monorepo_local-network
    depends_on:
      - backend
      - support-server
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    image: pitchlake-backend:latest  # Use the built image instead of build:
    platform: linux/amd64
    container_name: backend
    restart: unless-stopped
    environment:
      - PITCHLAKE_DB_URL=postgres://pitchlake_user:pitchlake_password@pitchlake-db:5432/pitchlake?sslmode=disable
      - FRONTEND_URL=http://frontend:3003
    depends_on:
      pitchlake-db:
        condition: service_healthy
    ports:
      - "3005:3005"
    networks:
      - fossil-monorepo_local-network

  support-server:
    build:
      context: support-server/
      dockerfile: Dockerfile
    image: pitchlake-support-server:latest  # Use the built image instead of build:
    platform: linux/amd64
    container_name: support-server
    restart: unless-stopped
    environment:
      # Database Connections
      - FOSSIL_DB_URL=postgresql://fossil_user:fossil_password@fossil-db:5432/fossil
      - PITCHLAKE_DB_URL=postgres://pitchlake_user:pitchlake_password@pitchlake-db:5432/pitchlake?sslmode=disable
      
      # Ethereum Configuration
      - L1_ALCHEMY_URL=${L1_ALCHEMY_URL}
      
      # StarkNet Configuration
      - STARKNET_RPC=http://katana:5050
      - STARKNET_PRIVATE_KEY=${STARKNET_PRIVATE_KEY}
      - STARKNET_ACCOUNT_ADDRESS=${STARKNET_ACCOUNT_ADDRESS}
      - VAULT_ADDRESSES=${VAULT_ADDRESSES}
      
      # Fossil API Configuration
      - FOSSIL_API_KEY=${FOSSIL_API_KEY}
      - FOSSIL_API_URL=${FOSSIL_API_URL}
      
      # Cron Schedules
      - CRON_SCHEDULE=${CRON_SCHEDULE:-*/5 * * * * *}
      - CRON_SCHEDULE_STATE=${CRON_SCHEDULE_STATE:-*/30 * * * * *}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # Optional: Demo mode
      - USE_DEMO_DATA=${USE_DEMO_DATA:-false}
    
    volumes:
      - ./logs:/app/logs
    
    networks:
      - fossil-monorepo_local-network
    
    depends_on:
      - fossil-db
      - pitchlake-db

  
volumes:
  fossil_data:
  pitchlake_data:

networks:
  fossil-monorepo_local-network:
    external: true
    name: fossil-monorepo_local-network 