version: "3.8"

services:
  pitchlake_websocket:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     FRONTEND_URL: ${FRONTEND_URL}
     PITCHLAKE_DB_URL: ${PITCHLAKE_DB_URL}
    ports:
      - "8080:8080" # Adjust this port if needed
