run:
  modules-download-mode: readonly
  timeout: 5m

version: "2"

linters:
  disable:
    - errcheck
    - ineffassign
    - staticcheck
  exclusions:
    paths:
      - juno

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
