
services:
  # Local database service (only used if pitchlake-db is not available)

  juno_plugin:
    volumes:
      - type: bind
        source: $HOME/snapshots-test/
        target: /snapshots

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VAULT_HASH: ${VAULT_HASH}
      UDC_ADDRESS: ${UDC_ADDRESS}
      RPC_URL: ${RPC_URL}
      L1_URL: ${L1_URL}
      CURSOR: ${CURSOR}
      DB_URL: ${DB_URL:-postgres://pitchlake_user:pitchlake_password@pitchlake-db:5432/pitchlake?sslmode=disable}
      DEPLOYER: ${DEPLOYER}
    networks:
      - pitchlake-network
    ports:
      - "6060:6060" # Adjust this port if needed

volumes:
  postgres_data:

networks:
  fossil-monorepo_local-network:
    external: true