name: Contracts Indexer

on:
  push:
    branches:
      - main
      - staging
    paths:
      - "contracts-indexer/**"
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "contracts-indexer/**"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
        with:
          files: contracts-indexer/
          extra-args: --file-extensions go

