name: Contracts Lint

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'contracts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'contracts/**'

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
        with:
          files: contracts/
          extra-args: --config contracts/_typos.toml

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1.5.0
      - name: Check Cairo formatting
        run: |
          cd contracts
          scarb fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1.5.0
      - name: Run Cairo linter
        run: |
          cd contracts
          scarb lint --test
          

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/setup-snfoundry@v4
      - uses: software-mansion/setup-scarb@v1.5.0
      - name: Run Cairo tests
        run: |
          cd contracts
          snforge test
